SELECT
  E.ID        AS ID,
  E.EMP_NO    AS EMP_NO,
  E.EMP_NAME  AS EMP_NAME,
  E.MGR_ID    AS MGR_ID,
  E.HIREDATE  AS HIREDATE,
  E.SAL       AS SAL,
  E.DEPT_ID   AS DEPT_ID,
  D.DEPT_NAME AS DEPT_NAME,
  D.DEPT_NO   AS DEPT_NO,
  D.LOC       AS LOC
FROM EMP E
INNER JOIN DEPT D ON E.DEPT_ID = D.ID
ORDER BY E.EMP_NO