create table DEPT (
    ID bigint generated by default as identity,
    DEPT_NO integer not null,
    DEPT_NAME varchar(20),
    LOC varchar(20),
    VERSION_NO integer,
    constraint DEPT_PK primary key(ID)
);
