create table EMP (
    ID bigint generated by default as identity,
    EMP_NO integer not null,
    EMP_NAME varchar(20),
    MGR_ID integer,
    HIREDATE date,
    SAL decimal(7,2),
    DEPT_ID integer,
    VERSION_NO integer,
    constraint EMP_PK primary key(ID)
);
